import { mkdirSync, writeFileSync, symlinkSync, rmSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
const WT = process.argv[2]; const N = await import(`${WT}/prototypes/shared-context-browser/neighborhood.mjs`);
const dir = join(WT, 'prototypes/shared-context-browser/neighborhood/zz_symlink_probe'); rmSync(dir, { recursive: true, force: true }); mkdirSync(dir);
symlinkSync('/etc/hosts', join(dir, 'leaked-note.md')); symlinkSync('/etc', join(dir, 'outside'));
writeFileSync(join(dir, 'door.json'), JSON.stringify({ door: '1', made_by: 'fx_probe', shared: 'probe', enter: { kind: 'local-module', ref: './outside/hosts' }, access: { may: ['enter'], may_not: [] }, origin: { world: 'zz-symlink-probe', revision: 1, published: '2026-09-14' }, notes: ['leaked-note.md', 'outside/hosts'], fixture: true }));
const d = JSON.parse(readFileSync(join(dir, 'door.json'), 'utf8'));
const R = []; const ok = (n, p, e) => { R.push(p); console.log(`${p ? '✓' : '✗'} ${n}${e ? ' — ' + e : ''}`); };
const v = N.validateDoor(d, dir);
ok('validation refuses the symlinked note(s)', v.problems.some((p) => /note .*(escape|symlink)/i.test(p)), v.problems.join(' | '));
ok('validation refuses the symlinked local-module ref', v.problems.some((p) => /enter\.ref/.test(p)), '');
const notes = N.notes({ ...d, dir, slug: 'zz_symlink_probe' });
ok('read refuses both notes, reads nothing', notes.every((n) => n.text === null && n.refused), notes.map((n) => `${n.file}: ${n.refused}`).join(' | '));
ok('nothing from /etc/hosts was read', !notes.some((n) => typeof n.text === 'string' && /localhost/.test(n.text)), '');
const e = await N.enter({ ...d, dir, slug: 'zz_symlink_probe' }).catch((err) => ({ world: null, reason: 'threw: ' + err.message.slice(0, 60) }));
ok('entry refuses the symlinked module', e.world === null && /refus|outside|symlink|escape/i.test(e.reason || ''), e.reason);
ok('doors() does not list the probe door', !N.doors().doors.some((x) => x.slug === 'zz_symlink_probe'), N.doors().rejected.filter((r) => r.slug === 'zz_symlink_probe').map((r) => r.problems.join(';')).join('') || 'not rejected-listed either');
rmSync(dir, { recursive: true, force: true });
console.log(`symlink-leg @${process.argv[3]}: ${R.filter(Boolean).length}/${R.length}`); process.exit(R.every(Boolean) ? 0 : 1);
